### ISSUE TITLE
mv Camera.service 

### ISSUE THREAD

**Issue by quintendewilde** [Frc2481/paul-bunyan#1]
Hi, I want to test you repository. But I get stuck when mv Camera.service to it's directory. 

I get mv: rename Camera.service to /lib/systemd/system/: No such file or directory

**Comment by Kython89** [comment]
What device are you running this on?  BeagleBoneBlack, RPi, Laptop?

What version of linux are you running?

**Comment by quintendewilde** [comment]
Sorry forgot the specs: Mac osx sierra (laptop)

**Comment by Kython89** [comment]
The instructions in the `README` are specifically meant for provisioning a Beagle Bone Black to run on the robot as a co-processor.  The lines your are specifically referencing install a `systemd` script  so the camera application will run when the system starts up.

Assuming you have installed the dependancies you are going to want to do the following.
`cd Camera`
`python main.py`
